### ISSUE TITLE
please upgrade visitor dep to 0.11

### ISSUE THREAD

**Issue by mariusa** [gagdiez/serial-as#39]
https://github.com/gagdiez/serial-as/blob/b7fac47a63e7a44c4437c8ddba43820f3679b29b/transform/package.json#L16

so that we can use it with latest assemblyscript

Thanks!

**Comment by mariusa** [comment]
Note: now it can't be used, gives this error, hope it's fixed in latest versions:

```
FAILURE /my-project/node_modules/assemblyscript/std/portable/index.js:198
    throw new AssertionError(message);
          ^

AssertionError: assertion failed
    at null.Z.assert (/my-project/node_modules/assemblyscript/std/portable/index.js:198:11)
    at Transformer._visit (/my-project/node_modules/@serial-as/transform/node_modules/visitor-as/src/base.ts:336:9)
    at Transformer.visit (/my-project/node_modules/@serial-as/transform/node_modules/visitor-as/src/visitor.ts:34:12)
    at null.<anonymous> (/my-project/node_modules/@serial-as/transform/node_modules/visitor-as/src/visitor.ts:21:31)
    at Array.map (<anonymous>)
    at Transformer.visit (/my-project/node_modules/@serial-as/transform/node_modules/visitor-as/src/visitor.ts:21:12)
    at Transformer.visitBlockStatement (/my-project/node_modules/@serial-as/transform/node_modules/visitor-as/src/base.ts:533:10)
    at Transformer._visit (/my-project/node_modules/@serial-as/transform/node_modules/visitor-as/src/base.ts:194:14)
    at Transformer.visit (/my-project/node_modules/@serial-as/transform/node_modules/visitor-as/src/visitor.ts:34:12)
    at Transformer.visitFunctionDeclaration (/my-project/node_modules/@serial-as/transform/node_modules/visitor-as/src/base.ts:625:10
```
